project:
  type: website
  render: 
    - "*.qmd"
    - "r_snacks/*.qmd"
    - "!r_snacks/index.qmd"
  output-dir: docs

execute: 
  freeze: true

website:
  title: "SSF data training"
  description: "Learn how to use R for small-scale fisheries data analysis"
  navbar:
    right:
      - icon: github
        href: https://github.com/WorldFishCenter/ssf.training/
format:
  html:
    theme: litera
    css: styles.css



