project:
  type: website
  render:
    - "*.qmd"
    - "r_snacks/*.qmd"
    - "!r_snacks/index.qmd"
  output-dir: docs

website:
  title: "R for SSF: Data Analysis Training"
  description: "Learn how to use R for small-scale fisheries data analysis"
  
  
  sidebar:
    style: "floating"
    search: true
    header: "Course contents:"
    contents:
      - section: "Getting Started"
        contents:
          - href: r_snacks/1_rbasics.qmd
            text: "1. R Installation"
          - href: r_snacks/2_rbasics.qmd
            text: "2. Basic Operations"
          - href: r_snacks/3_dataframes.qmd
            text: "3. Data Frames"
          - href: r_snacks/4_packages.qmd
            text: "4. Packages in R"
          - href: r_snacks/5_visualization.qmd
            text: "5. Data visualization"
      - section: "Data processing"
        contents:
          - href: r_snacks/6_preprocessing1.qmd
            text: "1. From messy to tidy data"
          - href: r_snacks/7_preprocessing2.qmd
            text: "2. A real case study"
      - section: "Data validation"
        contents:
          - href: r_snacks/8_validation1.qmd
            text: "1. Validation in fisheries data"
      - section: "Resources"
        contents:
          - href: r_snacks/9_references.qmd
            text: "1. Resources for Fisheries Analysis"

  navbar:
    logo: https://upload.wikimedia.org/wikipedia/en/9/9e/WorldFish_logo.svg           
    title: "R for Small-Scale Fisheries"  
    right:
      - text: "Tutorials"
        menu:
          - text: "Getting Started"
          - text: "1. R Installation"
            href: r_snacks/1_rbasics.qmd
          - text: "2. Basic Operations"
            href: r_snacks/2_rbasics.qmd
          - text: "3. Data Frames"
            href: r_snacks/3_dataframes.qmd
          - text: "4. Packages in R"
            href: r_snacks/4_packages.qmd
          - text: "5. Data visualization"
            href: r_snacks/5_visualization.qmd
          
          - text: "─────────────────"
          - text: "Data Processing"
          - text: "1. From messy to tidy data"
            href: r_snacks/6_preprocessing1.qmd
          - text: "2. A real case study"
            href: r_snacks/7_preprocessing2.qmd

          - text: "─────────────────"
          - text: "Data Validation"
          - text: "1. Validation in fisheries data"
            href: r_snacks/8_validation1.qmd

          - text: "─────────────────"
          - text: "Resources"
          - text: "1. Resources for Fisheries Analysis"
            href: r_snacks/9_references.qmd

      - icon: github
        href: https://github.com/WorldFishCenter/ssf.training/

  page-footer:
    left: "Copyright 2024 WorldFish"
    right:
      - icon: github
        href: https://github.com/WorldFishCenter/ssf.training/
  
  search:
    location: navbar
    type: overlay

format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: [cosmo, theme-dark.scss, custom.scss]
    toc: true
    toc-location: right
    toc-title: "On this page"
    code-fold: true
    code-tools: true
    code-link: true
    highlight-style: github
    css: styles.css
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px