project:
  type: website
  render:
    - "*.qmd"         # Applies to all .qmd files in the root
    - "r_snacks/*.qmd"  # Ensures all files within r_snacks are rendered
    - "!r_snacks/index.qmd"  # Exclude this if not needed
  output-dir: docs

website:
  description: "Learn how to use R for small-scale fisheries data analysis"
  navbar:
    logo: https://upload.wikimedia.org/wikipedia/en/9/9e/WorldFish_logo.svg
    right:
      - icon: github
        href: https://github.com/WorldFishCenter/ssf.training/
format:
  html:
    theme:
      light: [cosmo, custom.scss]  
      dark: [cosmo, theme-dark.scss, custom.scss]
